### ISSUE TITLE
Get Snapshot from AXIS

### ISSUE THREAD

**Issue by maguri** [FantasticFiasco/axis-configuration-js#716]
Hello @FantasticFiasco ,

I'm here because I found your repo is so nice and recently updated and I have a simple request.

I bought an [AXIS Q17 Network Camera Series](https://www.axis.com/products/axis-q17-series) and I need to implement a simple API with VAPX to get a Snapshot from the camera like this button:
![image](https://user-images.githubusercontent.com/14354821/95011770-5ee38580-0633-11eb-8772-e41bec6ca45e.png)

Please could you guide me a little? First time on it.

I think it should be something easy like this:
```
Header authentication
http://host:port/axis-cgi/jpg/image.cgi?someparams? 
```

Thanks in advanced

**Comment by FantasticFiasco** [comment]
Hi @maguri!

The short answer is this, you are correct. Send the request as a HTTP GET request with the correct authentication mechanism ([digest](https://en.wikipedia.org/wiki/Digest_access_authentication) is often the correct choice, but some of the cameras support [basic](https://en.wikipedia.org/wiki/Basic_access_authentication) although I wouldn't recommend it) and you'll get the picture as defined by the default media profile on your camera.

The long answer is this. I would recommend you to register to the [Axis Developer Community](https://www.axis.com/developer-community-intro), it doesn't cost you anything. Being part of the community you get access to the API documentation where for instance the options to the `image.cgi` are listed. The link to the specific information you require is [here](https://www.axis.com/vapix-library/subjects/t10037719/section/t10051110/display?section=t10051110-t10051110-t10003558-t10003575).

I don't think getting the image is suited for this library, but it opens up for me to create a new library directly tailored towards the image API. Would that be something you would be interested in using given it existed? And as a workaround until that exists, would you like me to see if I can write a small Node sample getting an image from a camera?

**Comment by maguri** [comment]
Thank you for your quick response @FantasticFiasco , 
I registered in the Community few minutes ago, Nice!, but don't find the Authentication Docs, anyway...

I m having troubles with the Digest Authentication to `/axis-cgi/jpg/image.cgi`, I get a **Forbidden 403**
Even that, Doing the same thing to `/axis-cgi/pwdgrp.cgi?action=get` and **it works!**

- Firmware 8.10 

![image](https://user-images.githubusercontent.com/14354821/95013710-5a729900-0642-11eb-8549-5af791444625.png)

`/axis-cgi/pwdgrp.cgi?action=get`

![image](https://user-images.githubusercontent.com/14354821/95013763-aae9f680-0642-11eb-8872-787ef5f116fa.png)

**Comment by FantasticFiasco** [comment]
I don't think firmware is the problem, but even so, upgrade to the latest version. I think you should end up in LTS 9.80 or in that same ballpark.

I just ran the request using Postman on a camera with firmware 9.80.2.2 and it worked as expected given I had chosen digest authentication with nothing added in the advanced settings, just as you have.

1. Do you see the same issue given you remove the query parameters?
2. You don't have a proxy on your network do you?

**Comment by FantasticFiasco** [comment]
I just noticed, you get `403 Forbidden` instead of `401 Unauthorized.` `Unauthorized` is what I'd expect if you'd enter a wrong password, but `Forbidden` indicates that your current user hasn't got the permissions to request the image API.

Have you been playing around with the users and the permissions of the `root` user?

**Comment by maguri** [comment]
No, didn't touch anything about permission, Am I have to add some license or something?, 

I already reset from factory and still doesn't working, I tried more the twice upgrade to 9.8 and 8.4 and the following error is raising: "The upgrade didn't work, so we're sending you back to try again." this is so weird, idk what else to do 🤦‍♂️.

**Comment by FantasticFiasco** [comment]
I don't think licenses are the issue. Not being able to upgrade is a huge problem and might be the underlying issue. I think you should report it on www.axis.com, because I don't think we'll be able to fix the image issue until we've fixed the underlying problem.

**Comment by maguri** [comment]
Agree!, I will close the Issue for now.
Thanks again!

**Comment by FantasticFiasco** [comment]
No problem at all, best wishes to you!

**Comment by maguri** [comment]
Definitely it was a problem with the camera, I could update Firmware, and works.
as simple as `/axis-cgi/jpg/image.cgi`

*Note: If you allow anonymous viewers No Auth is required.* ***Not recommended***

**Comment by FantasticFiasco** [comment]
Perfect, I hope your development journey goes smooth from here on!

**Comment by FantasticFiasco** [comment]
I've created a package for taking snapshots, you can find it [here](https://github.com/FantasticFiasco/axis-snapshot-js).
